"""add_main_chat_session_to_user

Revision ID: 2d0bf7624035
Revises: 492be0701c0c
Create Date: 2026-02-17 19:33:07.479789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0bf7624035'
down_revision: Union[str, Sequence[str], None] = '492be0701c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_chat_session_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'main_chat_session_id')
    # ### end Alembic commands ###
