"""add_project_metadata_to_session

Revision ID: 492be0701c0c
Revises: e7d6586949da
Create Date: 2026-02-17 17:00:47.302920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '492be0701c0c'
down_revision: Union[str, Sequence[str], None] = 'e7d6586949da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('cover_image_url', sa.String(length=1024), nullable=True))
    op.add_column('sessions', sa.Column('project_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'project_data')
    op.drop_column('sessions', 'cover_image_url')
    op.drop_column('sessions', 'category')
    op.drop_column('sessions', 'description')
    # ### end Alembic commands ###
