"""add_reference_image_to_entity

Revision ID: 541cf1448882
Revises: 5caf0549fbea
Create Date: 2026-01-29 15:25:13.724034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541cf1448882'
down_revision: Union[str, Sequence[str], None] = '5caf0549fbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('reference_image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'reference_image_url')
    # ### end Alembic commands ###
