"""Add user_id to Entity, make session_id optional

Revision ID: beb3ccfaa0d7
Revises: b7aba1b332a6
Create Date: 2026-02-01 23:18:07.618546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb3ccfaa0d7'
down_revision: Union[str, Sequence[str], None] = 'b7aba1b332a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. user_id'yi önce nullable olarak ekle
    op.add_column('entities', sa.Column('user_id', sa.UUID(), nullable=True))
    
    # 2. Mevcut entity'lerin user_id'sini session'larından al
    # Raw SQL ile güncelle
    op.execute("""
        UPDATE entities 
        SET user_id = sessions.user_id 
        FROM sessions 
        WHERE entities.session_id = sessions.id
    """)
    
    # 3. Hâlâ NULL olanları sil (orphan entity'ler)
    op.execute("""
        DELETE FROM entities WHERE user_id IS NULL
    """)
    
    # 4. user_id'yi NOT NULL yap
    op.alter_column('entities', 'user_id', nullable=False)
    
    # 5. session_id'yi nullable yap
    op.alter_column('entities', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # 6. Eski foreign key'i kaldır ve yenilerini ekle
    op.drop_constraint('entities_session_id_fkey', 'entities', type_='foreignkey')
    op.create_foreign_key('entities_user_id_fkey', 'entities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('entities_session_id_fkey', 'entities', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.create_foreign_key(op.f('entities_session_id_fkey'), 'entities', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entities', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('entities', 'user_id')
    # ### end Alembic commands ###
