"""add_smart_agent_fields_to_assets

Revision ID: c4585d7a8f4b
Revises: 541cf1448882
Create Date: 2026-01-30 16:59:56.907707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4585d7a8f4b'
down_revision: Union[str, Sequence[str], None] = '541cf1448882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_assets', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('generated_assets', sa.Column('parent_asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generated_assets', 'generated_assets', ['parent_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_assets', type_='foreignkey')
    op.drop_column('generated_assets', 'parent_asset_id')
    op.drop_column('generated_assets', 'is_favorite')
    # ### end Alembic commands ###
