"""add_user_preferences_table

Revision ID: e7d6586949da
Revises: beb3ccfaa0d7
Create Date: 2026-02-08 00:25:11.277547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7d6586949da'
down_revision: Union[str, Sequence[str], None] = 'beb3ccfaa0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('default_style', sa.String(length=50), nullable=False),
    sa.Column('default_image_model', sa.String(length=100), nullable=False),
    sa.Column('default_video_model', sa.String(length=100), nullable=False),
    sa.Column('default_video_duration', sa.Integer(), nullable=False),
    sa.Column('auto_face_swap', sa.Boolean(), nullable=False),
    sa.Column('auto_upscale', sa.Boolean(), nullable=False),
    sa.Column('auto_translate_prompts', sa.Boolean(), nullable=False),
    sa.Column('response_language', sa.String(length=10), nullable=False),
    sa.Column('favorite_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learned_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_entities_created_at'), 'entities', ['created_at'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_session_id'), 'entities', ['session_id'], unique=False)
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_session_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_created_at'), table_name='entities')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
